Repository Mackovlak/Tes_Project, pull requests merged in 2025-03, with the labels that each got.

#1 Adding React Routing
  package.json
  test-vite/src/App.jsx
  test-vite/src/landing.jsx
  test-vite/src/main.jsx
Labels: enhancement

#15 modal asset
  test-vite/src/Search_case.jsx
  test-vite/src/components/modal.jsx
Labels: bug, good first issue, invalid, question

#16 Feature Update: Asset Selection & Search Enhancements
  test-vite/package-lock.json
  test-vite/package.json
  test-vite/public/hp.png
  test-vite/src/App.jsx
  test-vite/src/Case.jsx
  test-vite/src/Search_case.jsx
  test-vite/src/components/app-accordion.jsx
  test-vite/src/components/app-sheetbar.jsx
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/assets-modal.jsx
  test-vite/src/components/login-form.jsx
  test-vite/src/components/modals-dialog.jsx
  test-vite/src/components/nav-projects.jsx
  test-vite/src/components/nav-user.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sc-shelter.jsx
  test-vite/src/components/sc-table.jsx
  test-vite/src/components/team-switcher.jsx
  test-vite/src/components/ui/accordion.jsx
  test-vite/src/components/ui/checkbox.jsx
  test-vite/src/components/ui/dialog.jsx
  test-vite/src/components/ui/input.jsx
  test-vite/src/components/ui/menubar.jsx
  test-vite/src/components/ui/scroll-area.jsx
  test-vite/src/components/ui/select.jsx
  test-vite/src/components/ui/sheet.jsx
  test-vite/src/components/ui/sidebar.jsx
  test-vite/src/components/ui/tabs.jsx
  test-vite/src/index.css
  test-vite/src/main.jsx
Labels: documentation, enhancement

#17 New Btn Contact and Btn Asset
  tailwind.config.js
  test-vite/src/Case.jsx
  test-vite/src/Search_case.jsx
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/assets-modal.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sc-table.jsx
Labels: enhancement

#32 Case To Wo
  test-vite/src/Case.jsx
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/service-work.jsx
  test-vite/src/main.jsx
  test-vite/src/work.jsx
Labels: enhancement

#31 🚀 feat: Improve Case Management with API Integration, Validation & UI Enhancements
  next-api/src/app/api/asset-information/route.js
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/case-information/route.js
  test-vite/src/Case.jsx
  test-vite/src/Case_table.jsx
  test-vite/src/Search_case.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sc-table.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/main.jsx
Labels: enhancement

#38 Enhance Asset & Case Information API with Validation, Filtering & Ownership Updates
  next-api/package-lock.json
  next-api/package.json
  next-api/prisma/client/index.js
  next-api/src/app/api/asset-information/[AssetID]/route.js
  next-api/src/app/api/asset-information/kepemilikan/[AssetID]/route.js
  next-api/src/app/api/asset-information/kepemilikan/route.js
  next-api/src/app/api/asset-information/kepemilikan/unowned/route.js
  next-api/src/app/api/asset-information/route.js
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/case-information/route.js
  test-vite/eslint.config.js
  test-vite/src/App.jsx
  test-vite/src/Case.jsx
  test-vite/src/Case_table.jsx
  test-vite/src/Contact_table.jsx
  test-vite/src/Search_case.jsx
  test-vite/src/bookings.jsx
  test-vite/src/components/app-accordion.jsx
  test-vite/src/components/app-sheetbar.jsx
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/assets-modal.jsx
  test-vite/src/components/info-case.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sc-table.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/service-material.jsx
  test-vite/src/components/service-mo_detail.jsx
  test-vite/src/components/service-tab.jsx
  test-vite/src/components/service-work.jsx
  test-vite/src/components/sn-input.jsx
  test-vite/src/components/ui/sidebar.jsx
  test-vite/src/components/ui/tabs.jsx
  test-vite/src/main.jsx
  test-vite/src/material_order.jsx
  test-vite/src/mo_detail.jsx
  test-vite/src/work.jsx
Labels: documentation, enhancement

#41 feat: Merge Feature with Feature-slamet and feature miku21 with additional echancement
  api/db_cdax_testing.sql
  next-api/prisma/client/index.js
  next-api/prisma/schema.prisma
  next-api/src/app/api/asset-information/[AssetID]/route.js
  next-api/src/app/api/asset-information/kepemilikan/[AssetID]/route.js
  next-api/src/app/api/asset-information/kepemilikan/route.js
  next-api/src/app/api/asset-information/kepemilikan/unowned/route.js
  next-api/src/app/api/asset-information/route.js
  next-api/src/app/api/case-information/route.js
  next-api/src/app/api/contact-information/check-contacts-affiliation/route.js
  next-api/src/app/api/contact-information/route.js
  next-api/src/app/api/product-information/[ProductNumber]/route.js
  next-api/src/app/api/product-information/product-type/route.js
  next-api/src/app/api/product-information/route.js
  next-api/src/app/api/site_account/check-company-affiliations/route.js
  next-api/src/app/api/site_account/route.js
  test-vite/src/Search_case.jsx
  test-vite/src/components/assets-modal.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-table.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/sn-input.jsx
Labels: enhancement
