Repository Mackovlak/Tes_Project, pull requests merged in 2025-10, with the labels that each got.

#112 Revisi project
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/case-information/case-notes/[NoteID]/route.js
  next-api/src/app/api/case-information/route.js
  test-vite/src/components/Export-Excel.jsx
  test-vite/src/layout/Logistic_Page.jsx
  test-vite/src/pages/Case.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/master_table.jsx
  test-vite/src/pages/services/service-bookingApo.jsx
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
  test-vite/src/pages/services/service-mo_detailApo.jsx
  test-vite/src/pages/services/service-work.jsx
Labels: Code Cleaning, Redesign Ui/UX, Small patch

#116 Progress 13.51
  next-api/src/app/api/material-order/batch-update/route.js
  next-api/src/app/api/material-order/material-order-line-items/[LineItemID]/route.js
  test-vite/src/components/Export-Excel.jsx
  test-vite/src/layout/Logistic_Page.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
  test-vite/src/pages/services/service-mo_detailApo.jsx
Labels: Small patch

#118 🏯 Pull Request: Base64 Signature Upload & PDF Rendering Enhancement
  next-api/src/app/api/user/[IDUser]/route.js
  test-vite/src/components/Equipment-Recipt-Form.jsx
  test-vite/src/components/SignaturePad.jsx
  test-vite/src/components/service-request-form.jsx
  test-vite/src/components/user-profile.jsx
  test-vite/src/pages/ErfCase.jsx
Labels: Redesign Ui/UX, Small patch

#119 Refactor Material Order Form Handling — Remove Redundant `moForm` Sta…
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
  test-vite/src/pages/services/service-mo_detailApo.jsx
Labels: Code Cleaning, Small patch
