Repository Mackovlak/Tes_Project, pull requests merged in 2025-09, with the labels that each got.

#88 Revisi project
  test-vite/src/layout/Ce_Page.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/CaseDetailApo.jsx
  test-vite/src/pages/CaseDetailCe.jsx
Labels: Redesign Ui/UX

#90 Refactor notification logic and enhance sidebar navigation
  next-api/package-lock.json
  next-api/package.json
  next-api/src/app/api/auth/login/route.js
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/case-information/route.js
  next-api/src/app/api/material-order/batch-update/route.js
  next-api/src/app/api/resources/route.js
  next-api/src/app/api/service-log/create-order/route.js
  next-api/src/app/api/user/[IDUser]/route.js
  next-api/src/app/api/user/route.js
  next-api/src/app/api/work-order/[WOID]/route.js
  server/server.mjs
  test-vite/public/Find_Case.png
  test-vite/public/Patner_Login.png
  test-vite/src/Home.jsx
  test-vite/src/components/CaseField.jsx
  test-vite/src/components/login-form.jsx
  test-vite/src/components/model/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sidebar/app-sidebar.jsx
  test-vite/src/components/sidebar/nav-main.jsx
  test-vite/src/components/sidebar/nav-projects.jsx
  test-vite/src/components/ui/tabs.jsx
  test-vite/src/layout/FrontDesk_Page.jsx
  test-vite/src/pages/Case.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/CaseDetailApo.jsx
  test-vite/src/pages/CaseDetailCe.jsx
  test-vite/src/pages/CaseDetailCeLead.jsx
  test-vite/src/pages/FlowCase.jsx
  test-vite/src/pages/SearchCase_V3.jsx
  test-vite/src/pages/master_table.jsx
  test-vite/src/pages/services/service-booking.jsx
  test-vite/src/pages/services/service-bookingApo.jsx
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
Labels: bug fix, Code Cleaning, Redesign Ui/UX

#92 Feature ferdi after merge
  next-api/src/app/api/contact-information/route.js
  next-api/src/app/api/failure/route.js
  next-api/src/app/api/mo-detaill/route.js
  next-api/src/app/api/otc-code/route.js
  next-api/src/app/api/repairClassCode/route.js
  next-api/src/app/api/subk-technician/route.js
  next-api/src/app/api/user/route.js
  test-vite/src/components/model/sc-modal.jsx
  test-vite/src/pages/master_table.jsx
Labels: good first issue, Redesign Ui/UX

#93 🏯 **Pull Request — Path of a Thousand Cases: Elegant Evolution**
  test-vite/src/pages/CaseDetail.jsx
Labels: enhancement, bug fix

#96 Revisi project
  next-api/src/app/api/case-information/[CaseID]/route.js
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/SearchCase_V3.jsx
  test-vite/src/pages/services/service-bookingApo.jsx
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
  test-vite/src/pages/services/service-mo_detailApo.jsx
Labels: bug fix

#100 Revisi project
  next-api/src/app/api/bookings/[BookingId]/route.js
  next-api/src/app/api/bookings/route.js
  next-api/src/app/api/site_account/[SiteAccountID]/route.js
  next-api/src/app/api/site_account/route.js
  test-vite/src/layout/Apo_Page.jsx
  test-vite/src/layout/Logistic_Page.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/SearchCase_V3.jsx
  test-vite/src/pages/services/service-bookingApo.jsx
  test-vite/src/pages/services/service-case.jsx
  test-vite/src/pages/services/service-materialApo.jsx
  test-vite/src/pages/services/service-mo_detailApo.jsx
  test-vite/src/pages/services/service-work.jsx
Labels: enhancement, bug fix, Redesign Ui/UX

#101 🎴 PR: Link Warranty Services to Material Order Creation for Existing Work Orders
  next-api/prisma/migrations/20250912071444_adding_service_catalog_id_to_work_order/migration.sql
  next-api/prisma/schema.prisma
  next-api/src/app/api/material-order/route.js
  next-api/src/app/api/service-log/create-order/route.js
  next-api/src/app/api/work-order/[WOID]/route.js
  next-api/src/app/api/workorder/[WOID]/route.js
  test-vite/src/components/model/sc-modal.jsx
  test-vite/src/pages/services/service-work.jsx
Labels: enhancement, bug fix, Redesign Ui/UX

#102 Progres 11.40
  test-vite/src/pages/CaseDetail.jsx
Labels: enhancement

#103 🏯 PR: Support Multiple Material Orders Creation + Return CT Key Field
  next-api/src/app/api/material-order/route.js
  next-api/src/app/api/service-log/create-order/route.js
  next-api/src/utils/generateID.js
  test-vite/src/components/model/sc-modal.jsx
  test-vite/src/layout/Logistic_Page.jsx
Labels: Underdevelopment, Small patch

#111 🏯 Pull Request: Enriched Action Logs, Owner Notifications & Service Flow Refinements
  next-api/.env-example
  next-api/lib/actionLogDispatcher.js
  next-api/lib/email.js
  next-api/src/app/api/actionlog/route.js
  next-api/src/app/api/material-order/batch-update/route.js
  next-api/src/app/api/sendEmail/route.js
  next-api/src/app/api/service-log/create-order/route.js
  server/server.mjs
  test-vite/.env-example
  test-vite/package-lock.json
  test-vite/package.json
  test-vite/src/components/model/sc-modal.jsx
  test-vite/src/pages/CaseDetail.jsx
  test-vite/src/pages/services/service-bookingApo.jsx
  test-vite/src/pages/services/service-case.jsx
Labels: enhancement, bug fix, Small patch
