Repository Mackovlak/Tes_Project, pull requests merged in 2025-05, with the labels that each got.

#54 🚀 Refactor and Enhance Booking API & Component Logic
  next-api/src/app/api/bookings/[BookingId]/route.js
  next-api/src/app/api/bookings/route.js
  next-api/src/app/api/contact-information/[contactId]/route.js
  test-vite/src/Search_case.jsx
  test-vite/src/components/quick-wo-input.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-work.jsx
  test-vite/src/main.jsx
Labels: enhancement

#62 progres 10.04
  next-api/prisma/migrations/20250510140735_add_case_resolution/migration.sql
  next-api/prisma/migrations/20250510220058_relasi_csr/migration.sql
  next-api/prisma/migrations/20250510224241_change_td/migration.sql
  next-api/prisma/migrations/20250511025338_change_int/migration.sql
  next-api/prisma/schema.prisma
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/caseResolution/[id_csr]/route.js
  next-api/src/app/api/caseResolution/route.js
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/sc-table.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/main.jsx
  test-vite/src/master_table.jsx
Labels: documentation, enhancement

#63 🆕 Pull Request: Introduce `SearchCommandBlock` as Predefined Function
  next-api/src/app/api/asset-information/route.js
  next-api/src/app/api/caseResolution/route.js
  next-api/src/app/api/site_account/route.js
  test-vite/src/Search_case.jsx
  test-vite/src/components/assets-modal.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/service-case.jsx
Labels: documentation, enhancement

#65 ✨ Feature: Excel Export, Address Fixes & Component Enhancements
  docker-compose.yml
  next-api/package-lock.json
  next-api/package.json
  next-api/prisma/schema.prisma
  next-api/src/app/api/bookings/[BookingId]/route.js
  next-api/src/app/api/bookings/route.js
  next-api/src/app/api/case-information/route.js
  next-api/src/app/api/material-order/[MOID]/route.js
  next-api/src/app/api/material-order/material-order-line-items/[LineItemID]/route.js
  next-api/src/app/api/material-order/route.js
  test-vite/package-lock.json
  test-vite/package.json
  test-vite/src/Search_case.jsx
  test-vite/src/components/Export-Excel.jsx
  test-vite/src/components/quick-wo-input.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/sc-select.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/service-material.jsx
  test-vite/src/components/service-mo_detail.jsx
  test-vite/src/components/service-work.jsx
  test-vite/src/main.jsx
  test-vite/src/master_table.jsx
Labels: enhancement

#68 Feature-ferdi-after-merge
  next-api/src/app/api/booking/route.js
  next-api/src/app/api/bookingDetails/[BookingDetailId]/route.js
  next-api/src/app/api/bookingDetails/route.js
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/caseResolution/[id_csr]/route.js
  next-api/src/app/api/otc-code/[OTCCode]/route.js
  next-api/src/app/api/otc-code/route.js
  next-api/src/app/api/repairClassCode/[Code]/route.js
  next-api/src/app/api/repairClassCode/route.js
  next-api/src/app/api/resource-account/[ResourceAccountId]/route.js
  next-api/src/app/api/service-log/[ServiceCatalogID]/route.js
  next-api/src/app/api/service-log/parts-catalog/[PARTNUMBER]/route.js
  next-api/src/app/api/service-log/route.js
  next-api/src/app/api/servicecatalog-parts/[PartNumber]/route.js
  test-vite/src/components/app-sidebar.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/main.jsx
  test-vite/src/master_table.jsx
Labels: enhancement

#71 Progres 07.40
  next-api/src/app/api/material-order/material-order-line-items/[LineItemID]/route.js
  next-api/src/app/api/service-log/create-order/route.js
  test-vite/package-lock.json
  test-vite/package.json
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/service-mo_detail.jsx
Labels: enhancement

#72 🚀 feat(logging): Implement ActionLog Model, API Routes & Entity-Level Audit Tracking
  next-api/prisma/migrations/20250515152902_adding_action_log_status/migration.sql
  next-api/prisma/migrations/20250515154022_adding_case_id_relation_to_action_log/migration.sql
  next-api/prisma/migrations/20250515164716_adding_log_description_action_log/migration.sql
  next-api/prisma/migrations/20250516022756_adding_ref_id_action_log/migration.sql
  next-api/prisma/schema.prisma
  next-api/src/app/api/actionlog/[ActionLogID]/route.js
  next-api/src/app/api/actionlog/route.js
  next-api/src/app/api/bookings/route.js
  next-api/src/app/api/case-information/[CaseID]/route.js
  next-api/src/app/api/case-information/route.js
  next-api/src/app/api/material-order/material-order-line-items/[LineItemID]/route.js
  test-vite/src/Search_case.jsx
  test-vite/src/components/sc-modal.jsx
  test-vite/src/components/service-booking.jsx
  test-vite/src/components/service-case.jsx
  test-vite/src/components/service-material.jsx
  test-vite/src/components/service-mo_detail.jsx
  test-vite/src/components/service-work.jsx
Labels: help wanted
